spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  data:
    redis:
      host: localhost
      port: 6379


redirect:
  kakaoUrl: ${LOCAL_BASE_URL}/login/oauth2/code/kakao
  googleUrl: ${LOCAL_BASE_URL}/login/oauth2/code/google
  naverUrl: ${LOCAL_BASE_URL}/login/oauth2/code/naver


base-url: ${LOCAL_BASE_URL}
